### PR TITLE
Presheaf ccc

### PR DESCRIPTION
**Pull request by bond15**

### CODE REVIEW

**Comment by bond15** [comment]
Still cleaning things up, but there are no holes left.

**Comment by bond15** [comment]
Trying to add all the new structure to Cubical.Categories.Preseheaf.Constructions .. 
but there is an annoying cyclic module dependency
  Cubical.Categories.Presheaf.Constructions
  Cubical.Categories.Exponentials
  Cubical.Categories.Limits.BinProduct.More
  Cubical.Categories.Presheaf.Constructions

**Review by hejohns — COMMENTED** [review]
nice! It looks like line lengths/whitespace are the only things failing the CI.

**Comment by maxsnew** [comment]
To fix the whitespace you can run the `fix-whitespace` utility. We should have instructions on how to install it in the readme but we don't seem to...
For the long line lengths, I added `(add-hook 'agda2-mode-hook 'column-enforce-mode)` to my `init.el`.

**Comment by maxsnew** [comment]
I haven't looked at the code yet, but `Presheaf.CCC` is not the typical naming scheme for this. It would probably go in `Presheaf.Properties` if that doesn't cause a circular dependency or just add it to the existing `Presheaf.Constructions`

**Comment by hejohns** [comment]
I tweaked the universe levels for $\top\mathcal P$ and $\times\mathcal P$ to simply be over $\mathsf{SET} \ell S$-valued presheaves, and moved them into a separate module from $\Rightarrow\mathcal P$ which *does* need the level of $\mathsf{SET}$ to be "high enough".

**Comment by hejohns** [comment]
note after meeting w/ @maxsnew:
should make presheaf operations more universe polymorphic, eg should be able to take a product of presheaves at $\ell A$ and $\ell B$ for a presheaf at $\ell \mathsf{-max}\ \ell A\ \ell B$

**Comment by bond15** [comment]
I missed these notifications. Looking into levels issue

**Comment by bond15** [comment]
I made the `PshProd` and `ExpOb` more universe polymorphic but I've run into an issue.

https://github.com/maxsnew/cubical-categorical-logic/blob/412ac9858ee4e57a5318b0ff695394fc0bd26e57/Cubical/Categories/Presheaf/CCC.agda#L133

The last remaining hole here is `refl` .. you can normalize the goal and lhs and rhs are exactly the same.
If you fill the hole with refl and attempt to typecheck, Agda runs out of memory.

**Comment by maxsnew** [comment]
Why bother doing a comp with `refl`? Why not just
```
h .N-ob y (Z .F-hom (y→x .lower) Zx , By)) (sym prf) ) 
```

**Comment by maxsnew** [comment]
Why bother doing a comp with `refl`? Why not just
```
 liftExt (cong (λ h → h .N-ob y (Z .F-hom (y→x .lower) Zx , By)) (sym prf)) 
```

**Comment by maxsnew** [comment]
I rebased onto main so make sure you reset locally

**Pull request merged**
