### PR TITLE
incremental Makefile

### PR DESCRIPTION
**Pull request by hejohns**
#89

### CODE REVIEW

**Comment by hejohns** [comment]
@maxsnew, what do you want to do about UMP.agda? It doesn't build right now.

**Comment by maxsnew** [comment]
Delete it but make an issue for us to reimplement what it had (which I think is really just preservation of products)

**Comment by maxsnew** [comment]
the sed script does not work on Mac OS X

**Comment by hejohns** [comment]
Oh I didn’t expect the macos basic regex to be slightly different than gnu
sed.
Will fix.

**Comment by maxsnew** [comment]
confirmed working on my machine:
```
> make clean
...
> time make
...
make  103.86s user 2.93s system 97% cpu 1:49.09 total
> time make
...
make  3.40s user 0.34s system 93% cpu 3.993 total
```

Thanks @hejohns !

**Pull request merged**
